# Generated by Django 3.2.17 on 2023-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='amrutha', max_length=80),
            preserve_default=False,
        ),
    ]
