# Generated by Django 3.2.17 on 2023-02-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='dept',
        ),
    ]
